In [1]:
import numpy as np

In [2]:
names=np.array(['ww','xly','fqw','lxy','qwm'])
names

array(['ww', 'xly', 'fqw', 'lxy', 'qwm'], 
      dtype='<U3')

In [3]:
sub=np.array(['m','e','p','c','a','d','ph'])
sub

array(['m', 'e', 'p', 'c', 'a', 'd', 'ph'], 
      dtype='<U2')

In [4]:
names.ndim

1

In [5]:
names.size

5

In [6]:
names.dtype

dtype('<U3')

In [7]:
names[2]

'fqw'

In [8]:
sub[-3]

'a'

In [9]:
sub[[0,2,4]]

array(['m', 'p', 'a'], 
      dtype='<U2')

In [10]:
names[1:4]

array(['xly', 'fqw', 'lxy'], 
      dtype='<U3')

In [11]:
sub[:-1:2]

array(['m', 'p', 'a'], 
      dtype='<U2')

In [12]:
names[(names=='ww')|(names=='qym')]

array(['ww'], 
      dtype='<U3')

In [13]:
scores=([[1,2,3],
        [4,5,6],
        [7,8,9]])
scores

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
scores.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [15]:
scores.size

AttributeError: 'list' object has no attribute 'size'

In [16]:
scores

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
scores=np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

In [18]:
scores.ndim

2

In [19]:
scores.size

9

In [20]:
scores.shape

(3, 3)

In [21]:
scores.dtype

dtype('int32')

In [22]:
scores[1,0]

4

In [23]:
scores[[1,2],[0,1]]

array([4, 8])

In [24]:
scores[[1,3]]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [25]:
scores[[1,2]]

array([[4, 5, 6],
       [7, 8, 9]])

In [26]:
scores[:,[0,1]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [27]:
scores[[0.2],1:2]

C:\Users\AliceKiller\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: VisibleDeprecationWarning: non integer (and non boolean) array-likes will not be accepted as indices in the future
  if __name__ == '__main__':


array([[2]])

In [28]:
scores[[1,2]][:,[0,1]]

array([[4, 5],
       [7, 8]])

In [29]:
scores[(names=='xly')|(names=='fqw'),:]

C:\Users\AliceKiller\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 5
  if __name__ == '__main__':


array([[4, 5, 6],
       [7, 8, 9]])

In [30]:
scores[(names=='xly')|(names=='fqw')][:,(sub=='m')|(sub=='p')]

C:\Users\AliceKiller\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 5
  if __name__ == '__main__':
C:\Users\AliceKiller\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 1; dimension is 3 but corresponding boolean dimension is 7
  if __name__ == '__main__':


array([[4, 6],
       [7, 9]])

In [31]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [33]:
np.arange(0.3,1.5,0.3)

array([ 0.3,  0.6,  0.9,  1.2])

In [34]:
np.arange(0,15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [36]:
np.ones((4,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])