In [1]:
import numpy as np
names = np.array(['王微', '肖良英', '方绮雯', '刘旭阳','钱易铭'])
subjects = np.array(['Math', 'English', 'Python', 'Chinese','Art', 'Database', 'Physics'])
scores = np.array([[70,85,77,90,82,84,89],[60,64,80,75,80,92,90],[90,93,88,87,86,90,91],[80,82,91,88,83,86,80],[88,72,78,90,91,73,80]])

In [2]:
print( scores + 5 )

[[75 90 82 95 87 89 94]
 [65 69 85 80 85 97 95]
 [95 98 93 92 91 95 96]
 [85 87 96 93 88 91 85]
 [93 77 83 95 96 78 85]]


In [3]:
bonus = np.array([3,4,5,3,6,7,2])
a=scores + bonus
a

array([[73, 89, 82, 93, 88, 91, 91],
       [63, 68, 85, 78, 86, 99, 92],
       [93, 97, 93, 90, 92, 97, 93],
       [83, 86, 96, 91, 89, 93, 82],
       [91, 76, 83, 93, 97, 80, 82]])

In [4]:
scores[names == '肖良英', subjects == 'English']

array([64])

In [5]:
scores[names == '肖良英', subjects == 'English'] + 5

array([69])

In [6]:
np.floor(scores/10)

array([[ 7.,  8.,  7.,  9.,  8.,  8.,  8.],
       [ 6.,  6.,  8.,  7.,  8.,  9.,  9.],
       [ 9.,  9.,  8.,  8.,  8.,  9.,  9.],
       [ 8.,  8.,  9.,  8.,  8.,  8.,  8.],
       [ 8.,  7.,  7.,  9.,  9.,  7.,  8.]])

In [7]:
np.subtract(scores, 3)

array([[67, 82, 74, 87, 79, 81, 86],
       [57, 61, 77, 72, 77, 89, 87],
       [87, 90, 85, 84, 83, 87, 88],
       [77, 79, 88, 85, 80, 83, 77],
       [85, 69, 75, 87, 88, 70, 77]])

In [8]:
scores.sum(axis = 0)

array([388, 396, 414, 430, 422, 425, 430])

In [9]:
scores[names == '王微'].mean() 

82.428571428571431

In [10]:
names[ scores[:,subjects == 'English'].argmax()

SyntaxError: unexpected EOF while parsing (<ipython-input-10-b34dd7d91454>, line 1)

In [11]:
names[ scores[:,subjects == 'English'].argmax()]

'方绮雯'

In [12]:
np.random.randint(0,6,10)

array([5, 2, 2, 2, 4, 1, 3, 0, 1, 1])

In [13]:
np.random.randint(0, 2, size = (5,6))

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 1, 1, 0, 1],
       [1, 1, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 1]])

In [14]:
np.random.normal( 0,1, size = (4,5) )

array([[-1.24471277,  0.65243818,  0.70132995, -1.31650662, -2.28497848],
       [ 1.7434326 ,  1.03326695, -0.47431116,  0.43853062,  1.13192733],
       [ 0.44524384, -1.15265405,  0.67059969,  0.31315755,  0.66881721],
       [-0.25272911, -1.21568247, -0.32790942,  0.67348036,  1.68521345]])